In [3]:
import requests
import json
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [4]:
def get_trip_data():
    # build url
    url = f'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/tour_dem_tttot?format=JSON&unit=NR&unit=NR&c_dest=EU27_2020_FOR&c_dest=EU27_2020_FOR&purpose=TOTAL&purpose=PER&purpose=PROF&purpose=TOTAL&purpose=PER&purpose=PROF&duration=N_GE1&duration=N1-3&duration=N_GE4&duration=N_GE1&duration=N1-3&duration=N_GE4&lang=en'
    url_text = requests.get(url)

    trip_dict = json.loads(url_text.text)

    return trip_dict

In [5]:
data = get_trip_data()
data

{'version': '2.0',
 'class': 'dataset',
 'label': 'Trips by duration, purpose and main destination',
 'source': 'ESTAT',
 'updated': '2025-02-27T23:00:00+0100',
 'value': {'2144': 31962,
  '1988': 1236012,
  '1989': 1897332,
  '1990': 4102510,
  '1991': 4675543,
  '1760': 1390863,
  '1761': 1680574,
  '1762': 3253301,
  '1763': 3678589,
  '1772': 37953,
  '1774': 102076,
  '1775': 193702,
  '2096': 1532374,
  '2097': 1259831,
  '2098': 2685401,
  '1904': 71908,
  '1905': 56478,
  '1906': 216308,
  '1907': 273609,
  '1784': 575544,
  '1785': 490169,
  '1786': 1301715,
  '1787': 1701345,
  '1808': 6360670,
  '1809': 8497900,
  '1810': 12972090,
  '1811': 14296783,
  '1796': 711631,
  '1797': 763901,
  '1798': 1143824,
  '1799': 1295918,
  '1748': 16914983,
  '1749': 21784674,
  '1750': 41682870,
  '1751': 49432386,
  '1820': 141893,
  '1821': 109548,
  '1822': 328393,
  '1823': 408300,
  '1844': 24894,
  '1845': 39806,
  '1846': 87513,
  '1847': 85435,
  '1856': 1060415,
  '1857': 1262913,
  '1858': 2761412,
  '1859': 3079819,
  '1736': 21072184,
  '1737': 25965957,
  '1738': 50368742,
  '1739': 59278730,
  '2060': 627826,
  '2061': 576630,
  '2062': 1276922,
  '2063': 2256584,
  '1868': 2242381,
  '1869': 2350138,
  '1870': 5563893,
  '1871': 7239099,
  '1880': 99031,
  '1881': 112656,
  '1882': 322486,
  '1883': 539127,
  '1952': 1047500,
  '1953': 858120,
  '1954': 1640254,
  '1955': 1734896,
  '1832': 234197,
  '1833': 125965,
  '1834': 718399,
  '1835': 959742,
  '1892': 647363,
  '1893': 550478,
  '1894': 1309087,
  '1895': 1339681,
  '1928': 118469,
  '1929': 146362,
  '1930': 236685,
  '1931': 292252,
  '1940': 427750,
  '1941': 533546,
  '1942': 798453,
  '1943': 919721,
  '1916': 188389,
  '1917': 143201,
  '1918': 445240,
  '1919': 517220,
  '2133': 19600,
  '1964': 41261,
  '1965': 54204,
  '1966': 116836,
  '1967': 148470,
  '1976': 1116399,
  '1977': 2449133,
  '1978': 4713208,
  '1979': 5291102,
  '2085': 485367,
  '2086': 1804450,
  '2087': 1705199,
  '2000': 859906,
  '2001': 979942,
  '2002': 1638227,
  '2003': 1822276,
  '2012': 137103,
  '2013': 159168,
  '2014': 476997,
  '2015': 713747,
  '2024': 37953,
  '2025': 57332,
  '2026': 134147,
  '2027': 206176,
  '2072': 886713,
  '2073': 1007355,
  '2074': 2725629,
  '2036': 401885,
  '2037': 633641,
  '2038': 897369,
  '2039': 1326847,
  '2048': 346273,
  '2049': 404999,
  '2050': 1085767,
  '2051': 1390715,
  '1712': 132097,
  '1556': 2745537,
  '1557': 5693822,
  '1558': 10335638,
  '1559': 11442751,
  '1328': 4725487,
  '1329': 6031294,
  '1330': 10582022,
  '1331': 11104802,
  '1340': 106281,
  '1341': 77016,
  '1342': 480738,
  '1343': 715572,
  '1664': 5077041,
  '1665': 5189364,
  '1666': 9399768,
  '1472': 252800,
  '1473': 298571,
  '1474': 767239,
  '1475': 1027870,
  '1352': 2094984,
  '1353': 2601456,
  '1354': 5277538,
  '1355': 5969617,
  '1376': 27454006,
  '1377': 37861817,
  '1378': 62702871,
  '1379': 69259601,
  '1364': 2265534,
  '1365': 2411296,
  '1366': 4069834,
  '1367': 4427008,
  '1316': 57774619,
  '1317': 83623396,
  '1318': 152498274,
  '1319': 169697612,
  '1388': 292016,
  '1389': 291253,
  '1390': 684636,
  '1391': 870169,
  '1412': 136195,
  '1413': 195950,
  '1414': 480715,
  '1415': 541750,
  '1424': 2435582,
  '1425': 3725116,
  '1426': 7871567,
  '1427': 8753200,
  '1304': 71270363,
  '1305': 99635202,
  '1306': 186411970,
  '1307': 207411206,
  '1628': 1478679,
  '1629': 1265344,
  '1630': 4216754,
  '1631': 4921417,
  '1436': 6040884,
  '1437': 8845429,
  '1438': 16791163,
  '1439': 19621815,
  '1448': 243030,
  '1449': 246873,
  '1450': 630558,
  '1451': 1013244,
  '1520': 1905161,
  '1521': 1976433,
  '1522': 4091998,
  '1523': 4586607,
  '1400': 850525,
  '1401': 862625,
  '1402': 3979938,
  '1403': 4572925,
  '1460': 1808737,
  '1461': 2718243,
  '1462': 5758578,
  '1463': 5503169,
  '1496': 337109,
  '1497': 421475,
  '1498': 910033,
  '1499': 1034779,
  '1508': 1138384,
  '1509': 1476294,
  '1510': 2149224,
  '1511': 2241401,
  '1484': 300743,
  '1485': 322014,
  '1486': 866247,
  '1487': 1027321,
  '1700': 32297,
  '1701': 104898,
  '1532': 105267,
  '1533': 187898,
  '1534': 398573,
  '1535': 515034,
  '1544': 5333024,
  '1545': 9750465,
  '1546': 17089385,
  '1547': 18356584,
  '1653': 1485517,
  '1654': 5359893,
  '1655': 5138460,
  '1568': 4464113,
  '1569': 4859746,
  '1570': 8183800,
  '1571': 9233197,
  '1580': 350379,
  '1581': 551443,
  '1582': 1333708,
  '1583': 1772674,
  '1592': 351892,
  '1593': 788563,
  '1594': 1262171,
  '1595': 1590037,
  '1640': 2307780,
  '1641': 3297295,
  '1642': 10547617,
  '1604': 981099,
  '1605': 1588407,
  '1606': 2331323,
  '1607': 2902947,
  '1616': 765137,
  '1617': 1289062,
  '1618': 2618100,
  '1619': 3214158,
  '2576': 100136,
  '2420': 1509525,
  '2421': 3796490,
  '2422': 6233127,
  '2423': 6767208,
  '2192': 3334623,
  '2193': 4350720,
  '2194': 7328722,
  '2195': 7426213,
  '2204': 68327,
  '2205': 52552,
  '2206': 378662,
  '2207': 521871,
  '2528': 3544666,
  '2529': 3929534,
  '2530': 6714367,
  '2336': 180892,
  '2337': 242093,
  '2338': 550931,
  '2339': 754261,
  '2216': 1519440,
  '2217': 2111287,
  '2218': 3975823,
  '2219': 4268272,
  '2240': 21093336,
  '2241': 29363917,
  '2242': 49730781,
  '2243': 54962819,
  '2228': 1553903,
  '2229': 1647396,
  '2230': 2926009,
  '2231': 3131091,
  '2180': 40859636,
  '2181': 61838722,
  '2182': 110815404,
  '2183': 120265225,
  '2252': 150123,
  '2253': 181704,
  '2254': 356242,
  '2255': 461869,
  '2276': 111301,
  '2277': 156144,
  '2278': 393202,
  '2279': 456314,
  '2288': 1375167,
  '2289': 2462203,
  '2290': 5110156,
  '2291': 5673381,
  '2168': 50198180,
  '2169': 73669245,
  '2170': 136043228,
  '2171': 148132476,
  '2492': 850854,
  '2493': 688714,
  '2494': 2939832,
  '2495': 2664833,
  '2300': 3798503,
  '2301': 6495291,
  '2302': 11227270,
  '2303': 12382716,
  '2312': 143999,
  '2313': 134217,
  '2314': 308072,
  '2315': 474117,
  '2384': 857661,
  '2385': 1118313,
  '2386': 2451744,
  '2387': 2851711,
  '2264': 616327,
  '2265': 736660,
  '2266': 3261539,
  '2267': 3613183,
  '2324': 1161374,
  '2325': 2167764,
  '2326': 4449491,
  '2327': 4163488,
  '2360': 218640,
  '2361': 275113,
  '2362': 673348,
  '2363': 742527,
  '2372': 710634,
  '2373': 942748,
  '2374': 1350771,
  '2375': 1321680,
  '2348': 112354,
  '2349': 178813,
  '2350': 421007,
  '2351': 510101,
  '2564': 24599,
  '2565': 85297,
  '2396': 64006,
  '2397': 133694,
  '2398': 281737,
  '2399': 366564,
  '2408': 4216625,
  '2409': 7301332,
  '2410': 12376177,
  '2411': 13065482,
  '2517': 1000149,
  '2518': 3555443,
  '2519': 3433261,
  '2432': 3604206,
  '2433': 3879804,
  '2434': 6545573,
  '2435': 7410921,
  '2444': 213276,
  '2445': 392276,
  '2446': 856712,
  '2447': 1058926,
  '2456': 313939,
  '2457': 731231,
  '2458': 1128025,
  '2459': 1383861,
  '2504': 1421067,
  '2505': 2289941,
  '2506': 7821988,
  '2468': 579214,
  '2469': 954766,
  '2470': 1433954,
  '2471': 1576100,
  '2480': 418864,
  '2481': 884063,
  '2482': 1532334,
  '2483': 1823443,
  '3284': 387488,
  '3285': 567916,
  '3286': 899093,
  '3287': 992572,
  '3056': 209609,
  '3057': 205170,
  '3058': 515291,
  '3059': 665427,
  '3394': 247026,
  '3200': 32199,
  '3202': 53754,
  '3203': 84815,
  '3080': 118811,
  '3082': 131109,
  '3083': 278260,
  '3104': 1458658,
  '3105': 1039158,
  '3106': 2503911,
  '3107': 3113362,
  '3093': 139958,
  '3094': 220353,
  '3095': 336177,
  '3044': 5031172,
  '3045': 4408747,
  '3046': 8910361,
  '3047': 10849306,
  '3116': 50396,
  '3117': 68442,
  '3118': 81101,
  '3119': 161216,
  '3140': 14626,
  '3142': 19846,
  '3143': 34704,
  '3152': 136833,
  '3153': 279096,
  '3154': 500574,
  '3155': 694891,
  '3032': 5954164,
  '3033': 5578967,
  '3034': 11171933,
  '3035': 13592123,
  '3356': 99344,
  '3357': 116753,
  '3358': 305993,
  '3359': 610843,
  '3164': 1237491,
  '3165': 982007,
  '3166': 1884368,
  '3167': 1594303,
  '3176': 27616,
  '3177': 34088,
  '3178': 72791,
  '3179': 164476,
  '3248': 161809,
  '3249': 158282,
  '3250': 240334,
  '3251': 239228,
  '3128': 52062,
  '3130': 112685,
  '3131': 180908,
  '3190': 242035,
  '3191': 338611,
  '3224': 68386,
  '3225': 78949,
  '3226': 122687,
  '3227': 152066,
  '3236': 114989,
  '3237': 95161,
  '3238': 156885,
  '3239': 232389,
  '3213': 29041,
  '3214': 68959,
  '3215': 116484,
  '3260': 20073,
  '3261': 24504,
  '3262': 23184,
  '3263': 43691,
  '3272': 635790,
  '3273': 381701,
  '3274': 881718,
  '3275': 970769,
  '3381': 121468,
  '3382': 505386,
  '3383': 546941,
  '3296': 232456,
  '3297': 302516,
  '3298': 443702,
  '3299': 606361,
  '3308': 78520,
  '3309': 74673,
  '3310': 154685,
  '3311': 168700,
  '3368': 359221,
  '3369': 476649,
  '3370': 1191986,
  '3332': 46715,
  '3333': 96628,
  '3334': 135166,
  '3335': 241247,
  '3345': 132969,
  '3346': 175633,
  '3347': 287832,
  '2852': 562146,
  '2853': 853530,
  '2854': 1381173,
  '2855': 1485735,
  '2624': 305558,
  '2625': 354139,
  '2626': 779364,
  '2627': 925544,
  '2638': 56596,
  '2639': 33645,
  '2960': 135518,
  '2962': 312630,
  '2768': 62808,
  '2769': 54801,
  '2770': 87225,
  '2771': 166477,
  '2648': 162560,
  '2649': 149655,
  '2650': 214442,
  '2651': 360557,
  '2672': 2412288,
  '2673': 2529169,
  '2674': 4504119,
  '2675': 5335734,
  '2661': 211733,
  '2662': 515663,
  '2663': 565903,
  '2612': 7496537,
  '2613': 7740490,
  '2614': 14607874,
  '2615': 16765707,
  '2684': 124651,
  '2685': 112677,
  '2686': 136645,
  '2687': 247065,
  '2708': 32769,
  '2709': 30285,
  '2710': 59738,
  '2711': 70613,
  '2720': 275433,
  '2721': 464412,
  '2722': 784577,
  '2723': 1067735,
  '2600': 9127088,
  '2601': 9904303,
  '2602': 18668161,
  '2603': 21273942,
  '2924': 273445,
  '2925': 189722,
  '2926': 775042,
  '2927': 916943,
  '2732': 1465727,
  '2733': 1242142,
  '2734': 2455680,
  '2735': 1956345,
  '2744': 48941,
  '2745': 70105,
  '2746': 158296,
  '2747': 277006,
  '2816': 238357,
  '2817': 244348,
  '2818': 441112,
  '2819': 456709,
  '2696': 70376,
  '2697': 51075,
  '2698': 159208,
  '2699': 332661,
  '2756': 255412,
  '2757': 397299,
  '2758': 583288,
  '2759': 722455,
  '2792': 135491,
  '2793': 166312,
  '2794': 330243,
  '2795': 355276,
  '2804': 182117,
  '2805': 150916,
  '2806': 243958,
  '2807': 336602,
  '2780': 37829,
  '2781': 64025,
  '2782': 114380,
  '2783': 185323,
  '2828': 37319,
  '2829': 40745,
  '2830': 43718,
  '2831': 80173,
  '2840': 830235,
  '2841': 505319,
  '2842': 1199460,
  '2843': 1281927,
  '2949': 281978,
  '2950': 828936,
  '2951': 790330,
  '2864': 604778,
  '2865': 751171,
  '2866': 1058602,
  '2867': 1219920,
  '2876': 133371,
  '2877': 134188,
  '2878': 288218,
  '2879': 301110,
  '2936': 537598,
  '2937': 789610,
  '2938': 1763666,
  '2900': 69492,
  '2901': 165328,
  '2902': 254541,
  '2903': 339122,
  '2913': 164300,
  '2914': 269001,
  '2915': 381859,
  '3716': 174658,
  '3717': 285614,
  '3718': 482079,
  '3719': 493163,
  '3488': 95949,
  '3489': 148969,
  '3490': 264073,
  '3491': 260117,
  '3634': 33471,
  '3635': 81662,
  '3515': 82297,
  '3536': 953630,
  '3537': 1490011,
  '3538': 2000208,
  '3539': 2222372,
  '3526': 295311,
  '3527': 229726,
  '3476': 2465365,
  '3477': 3331743,
  '3478': 5697514,
  '3479': 5916401,
  '3548': 74255,
  '3549': 44235,
  '3550': 55544,
  '3551': 85849,
  '3572': 18143,
  '3574': 39892,
  '3575': 35909,
  '3584': 138600,
  '3585': 185316,
  '3586': 284003,
  '3587': 372844,
  '3464': 3172924,
  '3465': 4325336,
  '3466': 7496228,
  '3467': 7681819,
  '3788': 174102,
  '3790': 469049,
  '3791': 306100,
  '3596': 228236,
  '3597': 260134,
  '3598': 571313,
  '3599': 362042,
  '3609': 36017,
  '3610': 85505,
  '3611': 112530,
  '3680': 76548,
  '3681': 86066,
  '3682': 200778,
  '3683': 217481,
  '3560': 18314,
  '3563': 151753,
  '3621': 257389,
  '3622': 341253,
  '3623': 383845,
  '3656': 67105,
  '3657': 87363,
  '3658': 207556,
  '3659': 203210,
  '3668': 67128,
  '3669': 55755,
  '3670': 87073,
  '3671': 104213,
  '3645': 34984,
  '3646': 45421,
  '3647': 68839,
  '3692': 17246,
  '3693': 16241,
  '3694': 20534,
  '3695': 36482,
  '3704': 194445,
  '3705': 123618,
  '3706': 317742,
  '3707': 311158,
  '3813': 160509,
  '3814': 323550,
  '3815': 243389,
  '3728': 372322,
  '3729': 448655,
  '3730': 614900,
  '3731': 613559,
  '3740': 54850,
  '3741': 59515,
  '3742': 133533,
  '3743': 132410,
  '3801': 312962,
  '3802': 571680,
  '3765': 68700,
  '3766': 119375,
  '3767': 97875,
  '3779': 94027,
  '848': 31962,
  '692': 1623500,
  '693': 2465248,
  '694': 5001604,
  '695': 5668115,
  '464': 1600472,
  '465': 1885744,
  '466': 3768591,
  '467': 4344017,
  '476': 44032,
  '477': 32958,
  '478': 136165,
  '479': 211736,
  '800': 1608619,
  '801': 1354631,
  '802': 2932426,
  '608': 104107,
  '609': 76025,
  '610': 270062,
  '611': 358424,
  '488': 694355,
  '489': 574492,
  '490': 1432824,
  '491': 1979605,
  '512': 7819329,
  '513': 9537058,
  '514': 15476000,
  '515': 17410145,
  '500': 756246,
  '501': 903859,
  '502': 1364177,
  '503': 1632095,
  '452': 21946155,
  '453': 26193421,
  '454': 50593230,
  '455': 60281692,
  '524': 192289,
  '525': 177990,
  '526': 409495,
  '527': 569516,
  '548': 39520,
  '549': 54113,
  '550': 107359,
  '551': 120139,
  '560': 1197247,
  '561': 1542008,
  '562': 3261986,
  '563': 3774710,
  '440': 27026347,
  '441': 31544924,
  '442': 61540674,
  '443': 72870853,
  '764': 727169,
  '765': 693383,
  '766': 1582915,
  '767': 2867427,
  '572': 3479872,
  '573': 3332146,
  '574': 7448261,
  '575': 8833402,
  '584': 126647,
  '585': 146744,
  '586': 395277,
  '587': 703603,
  '656': 1209309,
  '657': 1016402,
  '658': 1880588,
  '659': 1974124,
  '536': 286260,
  '537': 154692,
  '538': 831084,
  '539': 1140650,
  '596': 808305,
  '597': 690388,
  '598': 1551122,
  '599': 1678292,
  '632': 186855,
  '633': 225311,
  '634': 359373,
  '635': 444318,
  '644': 542739,
  '645': 628707,
  '646': 955338,
  '647': 1152110,
  '620': 209014,
  '621': 172242,
  '622': 514199,
  '623': 633704,
  '837': 20323,
  '668': 61334,
  '669': 78708,
  '670': 140020,
  '671': 192161,
  '680': 1752189,
  '681': 2830834,
  '682': 5594927,
  '683': 6261871,
  '789': 606836,
  '790': 2309836,
  '791': 2252139,
  '704': 1092363,
  '705': 1282458,
  '706': 2081929,
  '707': 2428637,
  '716': 215624,
  '717': 233840,
  '718': 631682,
  '719': 882447,
  '728': 37953,
  '729': 57332,
  '730': 134147,
  '731': 206176,
  '776': 1245935,
  '777': 1484003,
  '778': 3917615,
  '740': 448600,
  '741': 730270,
  '742': 1032536,
  '743': 1568094,
  '752': 525083,
  '753': 537968,
  '754': 1261400,
  '755': 1678547,
  '416': 138135,
  '260': 3307683,
  '261': 6547352,
  '262': 11716810,
  '263': 12928486,
  '32': 5031045,
  '33': 6385433,
  '34': 11361386,
  '35': 12030346,
  '44': 115995,
  '45': 91353,
  '46': 537334,
  '47': 749217,
  '368': 5212558,
  '369': 5326564,
  '370': 9712398,
  '176': 315607,
  '177': 353372,
  '178': 854464,
  '179': 1194347,
  '56': 2257544,
  '57': 2751111,
  '58': 5491980,
  '59': 6330174,
  '80': 29866294,
  '81': 40390986,
  '82': 67206989,
  '83': 74595336,
  '68': 2340991,
  '69': 2623030,
  '70': 4585497,
  '71': 4992912,
  '20': 65271156,
  '21': 91363886,
  '22': 167106148,
  '23': 186463318,
  '92': 416667,
  '93': 403930,
  '94': 821281,
  '95': 1117234,
  '116': 168964,
  '117': 226235,
  '118': 540453,
  '119': 612363,
  '128': 2711014,
  '129': 4189527,
  '130': 8656145,
  '131': 9820935,
  '8': 80397451,
  '9': 109539505,
  '10': 205080131,
  '11': 228685148,
  '332': 1752125,
  '333': 1455066,
  '334': 4991796,
  '335': 5838360,
  '140': 7506611,
  '141': 10087571,
  '142': 19246843,
  '143': 21578160,
  '152': 291971,
  '153': 316978,
  '154': 788854,
  '155': 1290250,
  '224': 2143518,
  '225': 2220781,
  '226': 4533110,
  '227': 5043316,
  '104': 920901,
  '105': 913700,
  '106': 4139146,
  '107': 4905586,
  '164': 2064150,
  '165': 3115542,
  '166': 6341867,
  '167': 6225624,
  '200': 472600,
  '201': 587787,
  '202': 1240276,
  '203': 1390055,
  '212': 1320501,
  '213': 1627211,
  '214': 2393182,
  '215': 2578003,
  '188': 338572,
  '189': 386040,
  '190': 980626,
  '191': 1212644,
  '404': 33055,
  '405': 106913,
  '236': 142586,
  '237': 228644,
  '238': 442291,
  '239': 595206,
  '248': 6163259,
  '249': 10255784,
  '250': 18288845,
  '251': 19638512,
  '357': 1767494,
  '358': 6188830,
  '359': 5928789,
  '272': 5068890,
  '273': 5610917,
  '274': 9242402,
  '275': 10453117,
  '284': 483750,
  '285': 685631,
  '286': 1621927,
  '287': 2073784,
  '296': 353978,
  '297': 791522,
  '298': 1272377,
  '299': 1590200,
  '344': 2845379,
  '345': 4086906,
  '346': 12311282,
  '308': 1050591,
  '309': 1753736,
  '310': 2585865,
  '311': 3242069,
  '320': 946265,
  '321': 1453362,
  '322': 2887101,
  '323': 3596017,
  '1280': 106173,
  '1124': 1684183,
  '1125': 4082104,
  '1126': 6715207,
  '1127': 7260371,
  '896': 3430573,
  '897': 4499689,
  '898': 7592795,
  '899': 7686329,
  '908': 71963,
  '909': 58396,
  '910': 401169,
  '911': 537481,
  '1232': 3603939,
  '1233': 3971934,
  '1234': 6779971,
  '1040': 211501,
  '1041': 277347,
  '1042': 584402,
  '1043': 835923,
  '920': 1563189,
  '921': 2176619,
  '922': 4059155,
  '923': 4350568,
  '944': 22046965,
  '945': 30853927,
  '946': 51730989,
  '947': 57185191,
  '932': 1584746,
  '933': 1719171,
  '934': 3221320,
  '935': 3360817,
  '884': 43325001,
  '885': 65170465,
  '886': 116512918,
  '887': 126181626,
  '956': 224378,
  '957': 225940,
  '958': 411786,
  '959': 547718,
  '980': 129444,
  '981': 172122,
  '982': 433094,
  '983': 492224,
  '992': 1513767,
  '993': 2647519,
  '994': 5394159,
  '995': 6046225,
  '872': 53371104,
  '873': 77994581,
  '874': 143539456,
  '875': 155814295,
  '1196': 1024955,
  '1197': 761683,
  '1198': 3408881,
  '1199': 2970934,
  '1004': 4026739,
  '1005': 6755425,
  '1006': 11798582,
  '1007': 12744758,
  '1016': 165324,
  '1017': 170234,
  '1018': 393577,
  '1019': 586647,
  '1088': 934209,
  '1089': 1204379,
  '1090': 2652522,
  '1091': 3069192,
  '968': 634642,
  '969': 759008,
  '970': 3308063,
  '971': 3764936,
  '1028': 1255844,
  '1029': 2425154,
  '1030': 4790744,
  '1031': 4547332,
  '1064': 285745,
  '1065': 362476,
  ...},
 'status': {'1772': 'u',
  '1773': 'u',
  '1905': 'u',
  '1844': 'u',
  '1845': 'u',
  '1739': 'e',
  '1833': 'u',
  '2132': 'u',
  '2133': 'u',
  '2024': 'u',
  '2025': 'u',
  '1307': 'e',
  '2204': 'u',
  '2205': 'u',
  '2171': 'e',
  '2348': 'u',
  '3068': 'u',
  '3069': 'u',
  '3070': 'u',
  '3071': 'u',
  '3392': 'u',
  '3393': 'u',
  '3394': 'u',
  '3200': 'u',
  '3201': 'u',
  '3202': 'u',
  '3080': 'u',
  '3081': 'u',
  '3082': 'u',
  '3105': 'u',
  '3092': 'u',
  '3093': 'u',
  '3094': 'u',
  '3116': 'u',
  '3140': 'u',
  '3141': 'u',
  '3142': 'u',
  '3143': 'u',
  '3035': 'e',
  '3356': 'u',
  '3357': 'u',
  '3176': 'u',
  '3177': 'u',
  '3129': 'u',
  '3130': 'u',
  '3131': 'u',
  '3188': 'u',
  '3189': 'u',
  '3190': 'u',
  '3191': 'u',
  '3212': 'u',
  '3213': 'u',
  '3428': 'u',
  '3429': 'u',
  '3260': 'u',
  '3381': 'u',
  '3368': 'u',
  '3369': 'u',
  '3370': 'u',
  '3332': 'u',
  '3344': 'u',
  '3345': 'u',
  '3346': 'u',
  '3008': 'u',
  '2636': 'u',
  '2637': 'u',
  '2638': 'u',
  '2639': 'u',
  '2960': 'u',
  '2961': 'u',
  '2962': 'u',
  '2768': 'u',
  '2769': 'u',
  '2648': 'u',
  '2649': 'u',
  '2650': 'u',
  '2660': 'u',
  '2661': 'u',
  '2708': 'u',
  '2709': 'u',
  '2603': 'e',
  '2925': 'u',
  '2744': 'u',
  '2745': 'u',
  '2697': 'u',
  '2698': 'u',
  '2756': 'u',
  '2757': 'u',
  '2780': 'u',
  '2781': 'u',
  '2996': 'u',
  '2997': 'u',
  '2888': 'u',
  '2889': 'u',
  '2890': 'u',
  '2891': 'u',
  '2900': 'u',
  '2912': 'u',
  '2913': 'u',
  '2914': 'u',
  '3872': 'u',
  '3500': 'u',
  '3501': 'u',
  '3502': 'u',
  '3503': 'u',
  '3824': 'u',
  '3825': 'u',
  '3826': 'u',
  '3632': 'u',
  '3633': 'u',
  '3634': 'u',

In [6]:
# improve modularity of function below
def transform_index(index, sizes):
    coords = []
    for size in reversed(sizes):
        coords.append(index % size)
        index //= size
    return list(reversed(coords))

In [7]:
def get_trip_df(trip_dict):
    # access dimensions & ids, size, category, label
    dimensions = trip_dict['dimension']
    dimension_ids = trip_dict['id']
    dimension_sizes = trip_dict['size']
    dimension_labels = {
        dim: dimensions[dim]['category']['label']
        for dim in dimension_ids
    }

    # set total_items to 1 so no multiply to 0
    total_items = 1
    for size in dimension_sizes:
        total_items *= size
    
    records = []
    for idx in range(total_items):
         # convert vals to strings
         key = str(idx)
         if key in trip_dict['value']:
             # transform datapoints into coordinates to access each oen
             coords = transform_index(idx, dimension_sizes)
             record = {}
             for i, dim in enumerate(dimension_ids):
                 label_keys = list(dimension_labels[dim].keys())
                 record[dim] = dimension_labels[dim][label_keys[coords[i]]]
             record['value'] = trip_dict['value'][key]
             records.append(record)
    df = pd.DataFrame(records)
    return df

In [8]:
trip_dict = get_trip_data()
trip_df = get_trip_df(trip_dict)

trip_df

,freq,c_dest,purpose,duration,unit,geo,time,value
0,Annual,EU27 countries (from 2020) except reporting co...,Total,1 night or over,Number,European Union - 27 countries (from 2020),2020,80397451
1,Annual,EU27 countries (from 2020) except reporting co...,Total,1 night or over,Number,European Union - 27 countries (from 2020),2021,109539505
2,Annual,EU27 countries (from 2020) except reporting co...,Total,1 night or over,Number,European Union - 27 countries (from 2020),2022,205080131
3,Annual,EU27 countries (from 2020) except reporting co...,Total,1 night or over,Number,European Union - 27 countries (from 2020),2023,228685148
4,Annual,EU27 countries (from 2020) except reporting co...,Total,1 night or over,Number,Euro area – 20 countries (from 2023),2020,65271156
...,...,...,...,...,...,...,...,...
1041,Annual,EU27 countries (from 2020) except reporting co...,"Professional, business",4 nights or over,Number,Sweden,2021,312962
1042,Annual,EU27 countries (from 2020) except reporting co...,"Professional, business",4 nights or over,Number,Sweden,2022,571680
1043,Annual,EU27 countries (from 2020) except reporting co...,"Professional, business",4 nights or over,Number,Norway,2021,160509
1044,Annual,EU27 countries (from 2020) except reporting co...,"Professional, business",4 nights or over,Number,Norway,2022,323550
1045,Annual,EU27 countries (from 2020) except reporting co...,"Professional, business",4 nights or over,Number,Norway,2023,243389

In [18]:
trip_df.rename(columns = {'purpose': 'Purpose', 'duration': 'Duration', 'geo': 'Country', 'time': 'Year', 'value': 'Num_Trips'}, inplace = True)
trip_df_filtered = trip_df[['Purpose', 'Duration', 'Country', 'Year', 'Num_Trips']]
trip_df_filtered

,Purpose,Duration,Country,Year,Num_Trips
0,Total,1 night or over,European Union - 27 countries (from 2020),2020,80397451
1,Total,1 night or over,European Union - 27 countries (from 2020),2021,109539505
2,Total,1 night or over,European Union - 27 countries (from 2020),2022,205080131
3,Total,1 night or over,European Union - 27 countries (from 2020),2023,228685148
4,Total,1 night or over,Euro area – 20 countries (from 2023),2020,65271156
...,...,...,...,...,...
1041,"Professional, business",4 nights or over,Sweden,2021,312962
1042,"Professional, business",4 nights or over,Sweden,2022,571680
1043,"Professional, business",4 nights or over,Norway,2021,160509
1044,"Professional, business",4 nights or over,Norway,2022,323550
1045,"Professional, business",4 nights or over,Norway,2023,243389