In [2]:
import requests
import json
import requests
import pandas as pd
from plotly import graph_objects as go
import plotly.graph_objects as go
import numpy as np

In [3]:
%run merge_data.ipynb
%run trips_duration.ipynb

Exception: File `'merge_data.ipynb'` not found.

In [74]:
df_merged 
fuel = df_merged[["Fuel Score"]].astype(float)
Fuel_standardize = (fuel -1) / (7-1)
density = df_merged[["Density Score"]].astype(float)
Density_standardize = (density -1) / (7-1)
df_merged["Fuel Score St."] = Fuel_standardize
df_merged["Density Score St."] = Density_standardize
df_merged_standardized = pd.DataFrame(df_merged, columns = ["Country", "Year", "Fuel Score St.", "Density Score St."])
df_merged_standardized['Year'] = df_merged_standardized['Year'].astype(int)    
df_merged_standardized

    Country  Year  Fuel Score St.  Density Score St.
0   Austria  2019        0.382700           0.772715
1   Austria  2021        0.304340           0.775648
2   Austria  2024        0.227270           0.749753
3   Belgium  2019        0.269300           1.000000
4   Belgium  2021        0.152768           1.000000
..      ...   ...             ...                ...
76    Spain  2021        0.234838           0.667055
77    Spain  2024        0.215143           0.667012
78   Sweden  2019        0.209655           0.539033
79   Sweden  2021        0.059442           0.528167
80   Sweden  2024        0.151893           0.530147

[81 rows x 4 columns]

In [93]:
df_merged_standardized.loc[df_merged_standardized['Country'] == 'Slovak Republic', 'Country'] = 'Slovakia'
df_merged_standardized['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden'], dtype=object)

In [94]:
fuel_density_2019 = df_merged_standardized[df_merged_standardized['Year'] == 2019]
fuel_density_2019
fuel_density_2019['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden'], dtype=object)

In [101]:
final_1plus_df

              Purpose         Duration      Country  Year  NumTrips
0    Personal Reasons  1 night or over      Albania  2017   8186685
1    Personal Reasons  1 night or over      Albania  2019  10176614
2    Personal Reasons  1 night or over      Albania  2020   6624361
3    Personal Reasons  1 night or over      Austria  2012  36003256
4    Personal Reasons  1 night or over      Austria  2013  36479782
..                ...              ...          ...   ...       ...
345  Personal Reasons  1 night or over  Switzerland  2018  40810491
346  Personal Reasons  1 night or over  Switzerland  2019  36986339
347  Personal Reasons  1 night or over  Switzerland  2020  31748407
348  Personal Reasons  1 night or over  Switzerland  2021  32989206
349  Personal Reasons  1 night or over  Switzerland  2022  46256337

[350 rows x 5 columns]

In [102]:
trips_2019 = final_1plus_df[final_1plus_df['Year'] == 2019]
trips_2019 = trips_2019[~trips_2019['Country'].isin([
    'European Union - 27 countries (from 2020)',
    'Albania',
    'Switzerland',
    'North Macedonia'
])]

print(len(trips_2019))

27

In [108]:
min_trips = trips_2019['NumTrips'].min()
max_trips = trips_2019['NumTrips'].max()

trips_2019['Tourism St.'] = (trips_2019['NumTrips'] - min_trips) / (max_trips - min_trips)

In [109]:
trips_2019.drop(columns = ['NumTrips', 'Duration'])
trips_2019['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden'], dtype=object)

In [110]:
recommender_data = pd.merge(fuel_density_2019, trips_2019, on = ['Country', 'Year'])
recommender_data

,Country,Year,Fuel Score St.,Density Score St.,Purpose,Duration,NumTrips,Tourism_Norm,Tourism St.
0,Austria,2019,0.382700,0.772715,Personal Reasons,1 night or over,42415052,0.093337,0.093337
1,Belgium,2019,0.269300,1.000000,Personal Reasons,1 night or over,33680649,0.073377,0.073377
2,Bulgaria,2019,0.491080,0.187095,Personal Reasons,1 night or over,9477196,0.018067,0.018067
3,Croatia,2019,0.344223,0.238313,Personal Reasons,1 night or over,10251772,0.019838,0.019838
4,Cyprus,2019,0.417000,0.709565,Personal Reasons,1 night or over,5753450,0.009558,0.009558
5,Czechia,2019,0.372012,0.836563,Personal Reasons,1 night or over,66969988,0.149450,0.149450
6,Denmark,2019,0.141125,0.934100,Personal Reasons,1 night or over,52037652,0.115327,0.115327
7,Estonia,2019,0.314100,0.688268,Personal Reasons,1 night or over,8753307,0.016413,0.016413
8,Finland,2019,0.193000,0.128237,Personal Reasons,1 night or over,66165686,0.147612,0.147612
9,France,2019,0.195800,1.000000,Personal Reasons,1 night or over,386709202,0.880119,0.880119
10,Germany,2019,0.264400,0.920948,Personal Reasons,1 night or over,439169070,1.000000,1.000000
11,Greece,2019,0.128600,0.457180,Personal Reasons,1 night or over,11562642,0.022833,0.022833
12,Hungary,2019,0.426402,1.000000,Personal Reasons,1 night or over,38102812,0.083483,0.083483
13,Ireland,2019,0.267900,0.717692,Personal Reasons,1 night or over,31378452,0.068116,0.068116
14,Italy,2019,0.149600,0.840430,Personal Reasons,1 night or over,109077864,0.245675,0.245675
15,Latvia,2019,0.380600,0.564368,Personal Reasons,1 night or over,7457030,0.013451,0.013451
16,Lithuania,2019,0.443600,0.683482,Personal Reasons,1 night or over,8598280,0.016059,0.016059
17,Luxembourg,2019,0.401600,1.000000,Personal Reasons,1 night or over,4143074,0.005878,0.005878
18,Malta,2019,0.284000,1.000000,Personal Reasons,1 night or over,1570905,0.000000,0.000000
19,Netherlands,2019,0.097100,1.000000,Personal Reasons,1 night or over,85166693,0.191033,0.191033
20,Poland,2019,0.436765,0.693278,Personal Reasons,1 night or over,121249320,0.273489,0.273489
21,Portugal,2019,0.205600,0.464300,Personal Reasons,1 night or over,37152910,0.081312,0.081312
22,Romania,2019,0.435555,0.187383,Personal Reasons,1 night or over,37503804,0.082114,0.082114
23,Slovakia,2019,0.322500,0.470255,Personal Reasons,1 night or over,24106768,0.051499,0.051499
24,Slovenia,2019,0.351900,1.000000,Personal Reasons,1 night or over,8610043,0.016086,0.016086
25,Spain,2019,0.344200,0.667213,Personal Reasons,1 night or over,291426796,0.662379,0.662379
26,Sweden,2019,0.209655,0.539033,Personal Reasons,1 night or over,89854108,0.201745,0.201745

In [ ]:
# FINAL DATA TO BE USED FOR FIRST ML MODEL!!!!!
# MARIA AND GABBY ARE SO SO HAPPY ON 6/5/2025 (gabbys birthday!) at 1:43 am!!!!!
recommender_data = pd.DataFrame(recommender_data, columns = ['Country', 'Year', 'Fuel Score St.', 'Density Score St.', 'Tourism St.'])
recommender_data

        Country  Year  Fuel Score St.  Density Score St.  Tourism St.
0       Austria  2019        0.382700           0.772715     0.093337
1       Belgium  2019        0.269300           1.000000     0.073377
2      Bulgaria  2019        0.491080           0.187095     0.018067
3       Croatia  2019        0.344223           0.238313     0.019838
4        Cyprus  2019        0.417000           0.709565     0.009558
5       Czechia  2019        0.372012           0.836563     0.149450
6       Denmark  2019        0.141125           0.934100     0.115327
7       Estonia  2019        0.314100           0.688268     0.016413
8       Finland  2019        0.193000           0.128237     0.147612
9        France  2019        0.195800           1.000000     0.880119
10      Germany  2019        0.264400           0.920948     1.000000
11       Greece  2019        0.128600           0.457180     0.022833
12      Hungary  2019        0.426402           1.000000     0.083483
13      Ireland  2019        0.267900           0.717692     0.068116
14        Italy  2019        0.149600           0.840430     0.245675
15       Latvia  2019        0.380600           0.564368     0.013451
16    Lithuania  2019        0.443600           0.683482     0.016059
17   Luxembourg  2019        0.401600           1.000000     0.005878
18        Malta  2019        0.284000           1.000000     0.000000
19  Netherlands  2019        0.097100           1.000000     0.191033
20       Poland  2019        0.436765           0.693278     0.273489
21     Portugal  2019        0.205600           0.464300     0.081312
22      Romania  2019        0.435555           0.187383     0.082114
23     Slovakia  2019        0.322500           0.470255     0.051499
24     Slovenia  2019        0.351900           1.000000     0.016086
25        Spain  2019        0.344200           0.667213     0.662379
26       Sweden  2019        0.209655           0.539033     0.201745

In [112]:
def normalize_user_input(user_input):
    """
    Takes in user preferences on a 0-10 scale for:
    - fuel: importance on saving fuel prices
    - traffic: importance avoiding traffic
    - tourism: importance of avoiding high-tourism countries

    Returns: a normalized array on a 0-1 scale
    """
    max_scale = 10
    weights = np.array([
        user_input['fuel_price'] / max_scale,
        user_input['traffic_time'] / max_scale,
        user_input['tourism_num'] / max_scale
    ])
    return weights

In [120]:
# example input
user_input = {
    'fuel_price': 8,
    'traffic_time': 5,
    'tourism_num': 9
}

user_weights = normalize_user_input(user_input)
print(user_weights)

[0.8 0.5 0.9]

In [1]:
def compute_weighted_distace(row, weights):
    """
    Computes weighted distance between one country and the ideal distance vector ([0,0,0])
    """

    ideal_vector = np.array([0.0, 0.0, 0.0])
    
    country_vector = np.array([
        row["Fuel Score St."], 
        row["Density Score St."], 
        row["Tourism St."]
    ])
    diff = (country_vector - ideal_vector) * weights 

    return np.linalg.norm(diff)

In [129]:
def get_top_5_recommendations(user_input, recommender_data): 
    """Reccomends top 5 countries closest to vector logo """

    user_weights = normalize_user_input(user_input)

    ideal_vector = np.array([0.0, 0.0, 0.0])

    recommender_data = recommender_data.copy()
    recommender_data["Distance"] = recommender_data.apply(
        lambda row: compute_weighted_distace(row, user_weights), axis = 1
    )

    top_5_recommendations = recommender_data.sort_values("Distance").head(5)
    return top_5_recommendations[["Country", "Distance"]]

In [151]:
user_input = {
    "fuel_price": 0,
    "traffic_time": 5,
    "tourism_num": 10
}

top_5 = get_top_5_recommendations(user_input, recommender_data)
print(top_5)

     Country  Distance
2   Bulgaria  0.095276
3    Croatia  0.120797
22   Romania  0.124583
8    Finland  0.160936
11    Greece  0.229728